config/routes.rb
Rails.application.routes.draw do
  resources :sections do
    post 'question/create', to: 'questions#create', as: :create_question
    patch 'question/update', to: 'questions#update', as: :update_question
    delete 'question/destroy', to: 'questions#destroy', as: :destroy_question
  end
  resources :chapters
  resources :evaluations
  devise_for :users

  authenticated(:user) do
    root 'pages#index', as: :authenticated_root
  end

  unauthenticated(:user) do 
    root 'pages#landing_page'
  end
  #root 'index#landing_page'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :section
  enum question_type: [:default, :text_free, :multiple, :level]
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :user
  has_many :questions, dependent: :destroy
  enum section_type: [:default, :evaluation, :chapter]

  scope :grab_all_evaluations, -> { where(section_type: 1) }
  scope :grab_all_chapters, -> { where(section_type: 2) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable
  has_many :sections       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: %i[ show edit update destroy ]

  # GET /chapters or /chapters.json
  def index
    @chapters = Section.grab_all_chapters
  end

  # GET /chapters/1 or /chapters/1.json
  def show
  end

  # GET /chapters/new
  def new
    @chapter = Section.new
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters or /chapters.json
  def create
    @chapter = current_user.sections.build(chapter_params)
    @chapter.section_type = 2

    respond_to do |format|
      if @chapter.save
        format.turbo_stream { 
          render turbo_stream: turbo_stream.replace('chapters_all', 
                                                     partial: 'chapters/chapters',
                                                    locals: {chapters: Section.grab_all_chapters}) }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1 or /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.turbo_stream { render turbo_stream: turbo_stream.replace("section_#{@chapter.id}",
                                                                        partial: 'chapters/card_chapter',
                                                                        locals: { chapter: @chapter }) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1 or /chapters/1.json
  def destroy
    @chapter.destroy

    respond_to do |format|
      format.html { redirect_to chapters_url, notice: "Chapter was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Section.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chapter_params
      params.require(:section).permit(:name, :description,  :body)
    end
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  before_action :set_evaluation, only: %i[ show edit update destroy ]

  # GET /evaluations or /evaluations.json
  def index
    @evaluations = Section.grab_all_evaluations
  end

  # GET /evaluations/1 or /evaluations/1.json
  def show
    @question = Question.new
  end

  # GET /evaluations/new
  def new
    @evaluation = Section.new
  end

  # GET /evaluations/1/edit
  def edit
  end

  # POST /evaluations or /evaluations.json
  def create
    @evaluation = current_user.sections.build(evaluation_params)
    @evaluation.section_type = 1

    respond_to do |format|
      if @evaluation.save
        format.turbo_stream { 
          render turbo_stream: turbo_stream.replace('evaluations_all', 
                                                     partial: 'evaluations/evaluations',
                                                    locals: {evaluations: Section.grab_all_evaluations}) }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluations/1 or /evaluations/1.json
  def update
    respond_to do |format|
      if @evaluation.update(evaluation_params)
        format.turbo_stream { render turbo_stream: turbo_stream.replace("section_#{@evaluation.id}",
                                                  partial: 'evaluations/evaluation',
                                                  locals: { evaluation: @evaluation }) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluations/1 or /evaluations/1.json
  def destroy
    @evaluation.destroy

    respond_to do |format|
      format.html { redirect_to evaluations_url, notice: "Evaluation was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluation
      @evaluation = Section.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def evaluation_params
      params.require(:section).permit(:name, :description, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def landing_page
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def create
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/chapters/_card_chapter.html.erb
<%= turbo_frame_tag 'modal' %>
<section id="<%= dom_id @chapter %>" class="border-2 w-9/12 mx-auto flex h-40 rounded-lg shadow-lg p-2 my-5">
  
  <div class="w-40">
    <%= image_tag("Upload.png", class: "object-fit h-full w-full") %>
  </div>

  <div class="p-5 w-full">
    <p class="text-3xl font-bold text-chapterStrong">
      <%= @chapter.name %> 
      <i class="fa-solid fa-list-check ml-5"></i>
    </p>

    <p class="my-2 font-semibold text-chapterStrong">
      Description:
      <%= @chapter.description %>
    </p>

    <p class="font-semibold text-sm text-chapterStrong">
      User:
      <%= @chapter.user_id %>
    </p>
  </div>

  <div class="border-2 flex flex-col justify-between p-2">
    <%= link_to edit_chapter_path(@chapter) , id: "edit_chapter_icon", data: {turbo_frame: 'modal'} do %>
      <i class="fa-solid fa-pen text-editIcon"></i>
    <% end %>  
    <%= button_to chapter_path(@chapter), id: 'remove_chapter_icon', method: :delete,
        form: {data: {turbo_confirm: 'Are you sure?'}} do %>
     <i class="fa-solid fa-trash text-removeIcon"></i>
    <% end %>
  </div>
</section>

app/views/chapters/_chapter.html.erb
<div id="<%= dom_id chapter %>" class="border-2 w-9/12 mx-auto flex h-40 rounded-lg shadow-lg p-2 my-5">
  <div class="w-40">
    <%= image_tag("Upload.png", class: "object-fit h-full w-full") %>
  </div>
  <div class="w-full p-5">
    <p>
      Name:
      <strong class="font-semibold">
        <%= chapter.name %> 
      </strong>
    </p>

    <p>
      Description:
      <strong class="font-semibold">
      <%= chapter.description %>
      </strong>
    </p>

    <p>
      User:
      <strong class="font-semibold">
      <%= chapter.user_id %>
      </strong>
    </p>
    <div class="flex justify-end">
      <%= button_to chapter_path(chapter), method: :get do %>
        <div class="rounded-lg bg-chapterStrong px-5 py-2 text-white text-sm font-semibold">
          Show chapter
        </div>
      <% end %>  
    </div>
  </div>


</div>

app/views/chapters/_chapters.html.erb
 <%= turbo_frame_tag 'modal' %>
<section id="chapters_all">
  
  <div class="py-10 flex flex-col w-full">
    <h2 class="py-5 text-3xl text-chapterStrong font-bold text-center">chapters</h2>
    <p class="text -sm text-center text-chapterStrong font-semibold">
      Loreme ipsum dolor sit amet, consectetur adipisicing elit. Odio, assumenda quas, <br>
       magni eos, fuga eum consequuntur totam nesciunt ipsum aperiam repellat aliquid
      <br> similique? Quam dicta ipsam earum aut officia inventore.
    </p>
  </div>

  <div class="flex justify-center py-5">
    <%= link_to new_chapter_path , id: "create_chapter_welcome", data: {turbo_frame: 'modal'} do %>
    <div class="p-3 bg-chapterStrong text-white text-sm font-semibold, rounded-lg">
     Create chapter
    </div>
    <% end %>
  </div>
   <% chapters.each do |chapter| %>
     <%= render 'chapter', chapter: chapter %>
   <% end %>
</section>

app/views/chapters/_form.html.erb
<%= form_with(model: @chapter, url: url, data: { controller: "reset", action: "submit->reset#resetForm"}) do |f|%>
  
  <div class="flex flex-col py-4">
    <%= f.label :name, class: "text-white font-semibold" %>
    <%= f.text_field :name, class: "p-2 rounded-lg font-semibold" %>
  </div>

   <div class="flex flex-col py-4">
    <%= f.label :description, class: "text-white font-semibold" %>
    <%= f.text_field :description, class: "p-2 rounded-lg font-semibold" %>
  </div>

  <div class="flex  py-2 justify-end gap-5">
    <span class="bg-chapterStrong p-2 rounded-lg">
      <%= f.submit  'Save chapter', class: "text-white font-semibold" %>
    </span>
    <span class="bg-removeIcon p-2 rounded-lg">
      <%= link_to "cancel", :back, class:"text-white font-sembibold" %>
    </span>  
  </div>
<% end %>

app/views/chapters/_welcome.html.erb
 <%= turbo_frame_tag 'modal' %>
<section class="flex flex-row-reverse justify-around items-center p-32" id="chapters_all">
  <div>
    <%= image_tag("4884176.jpg", width: '500')%> 
  </div>
  <div>
    <h1 class="tex-center text-3xl font-bold text-chapterStrong">Chapters PENDE</h1>
    <p class="text-center py-2 font-semibold text-chapterStrong">
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Autem maiores veniam odit <br> 
      necessitatibus quia cum fuga officiis eveniet saepe eligendi, qui repellendus perspiciatis  <br>
      natus consequatur doloribus, alias incidunt. Voluptates, possimus?</p>
    <div class="flex justify-center my-4">
      <%= link_to new_chapter_path , id: "create_chapter_welcome", data: {turbo_frame: 'modal'} do%>
        <div class="p-3 bg-chapterStrong text-white text-sm font-semibold rounded-lg">
         Create Chapter
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/chapters/edit.html.erb
<%= render 'shared/modal', title: 'Edit Chapter'  do%>
  <%= render 'form', url: chapter_path(@chapter) %>
<% end %>

app/views/chapters/index.html.erb
<%= turbo_frame_tag 'modal' %>
<% if @chapters.any? %>
 <%= render 'chapters', chapters: @chapters %>
<% else %> 
 <%= render 'welcome' %>
<% end %> 

app/views/chapters/new.html.erb
<%= render 'shared/modal', title: 'Create chapter'  do%>
  <%= render 'form', url: chapters_path %>
<% end %>

app/views/chapters/show.html.erb
<%= turbo_frame_tag 'modal' %>
<%= render 'card_chapter'%>

app/views/evaluations/_evaluation.html.erb
<div id="<%= dom_id evaluation %>" class="border-2 w-9/12 mx-auto flex h-40 rounded-lg shadow-lg p-2 my-5">
  <div class="w-40">
    <%= image_tag("Upload.png", class: "object-fit h-full w-full") %>
  </div>
  <div class="w-full p-5">
    <p>
      Name:
      <strong class="font-semibold">
        <%= evaluation.name %> 
      </strong>
    </p>

    <p>
      Description:
      <strong class="font-semibold">
      <%= evaluation.description %>
      </strong>
    </p>

    <p>
      User:
      <strong class="font-semibold">
      <%= evaluation.user_id %>
      </strong>
    </p>
    <div class="flex justify-end">
      <%= button_to evaluation_path(evaluation), method: :get do %>
        <div class="rounded-lg bg-evaluationStrong px-5 py-2 text-white text-sm font-semibold">
          See more
        </div>
      <% end %>  
    </div>
  </div>


</div>

app/views/evaluations/_evaluations.html.erb
 <%= turbo_frame_tag 'modal' %>
<section id="evaluations_all">
  
  <div class="py-10 flex flex-col w-full">
    <h2 class="py-5 text-3xl text-evaluationStrong font-bold text-center">Evaluations</h2>
    <p class="text -sm text-center text-evaluationStrong font-semibold">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, assumenda quas, <br>
       magni eos, fuga eum consequuntur totam nesciunt ipsum aperiam repellat aliquid
      <br> similique? Quam dicta ipsam earum aut officia inventore.
    </p>
  </div>

  <div class="flex justify-center py-5">
    <%= link_to new_evaluation_path , id: "create_evaluation_welcome", data: {turbo_frame: 'modal'} do %>
    <div class="p-3 bg-evaluationStrong text-white text-sm font-semibold, rounded-lg">
     Create evaluation
    </div>
    <% end %>
  </div>
   <% evaluations.each do |evaluation| %>
     <%= render 'evaluation', evaluation: evaluation %>
   <% end %>
</section>

app/views/evaluations/_form.html.erb
<%= form_with(model: @evaluation, url: url, data: { controller: "reset", action: "submit->reset#resetForm"}) do |f|%>
  
  <div class="flex flex-col py-4">
    <%= f.label :name, class: "text-white font-semibold" %>
    <%= f.text_field :name, class: "p-2 rounded-lg font-semibold" %>
  </div>

   <div class="flex flex-col py-4">
    <%= f.label :description, class: "text-white font-semibold" %>
    <%= f.text_field :description, class: "p-2 rounded-lg font-semibold" %>
  </div>

  <div class="flex  py-2 justify-end gap-5">
    <span class="bg-evaluationStrong p-2 rounded-lg">
      <%= f.submit  'Save evaluation', class: "text-white font-semibold" %>
    </span>
    <span class="bg-removeIcon p-2 rounded-lg">
      <%= link_to "cancel", :back, class:"text-white font-sembibold" %>
    </span>  
  </div>
<% end %>

app/views/evaluations/_marco.html.erb
holaaa

app/views/evaluations/_welcome.html.erb
 <%= turbo_frame_tag 'modal' %>
<section class="flex justify-around items-center p-32" id="evaluations_all">
  <div>
    <%= image_tag("6099984.jpg", width: '400')%>
  </div>
  <div>
    <h1 class="tex-center text-3xl font-bold text-evaluationStrong">Evaluations</h1>
    <p class="text-center py-2 font-semibold text-evaluationStrong">
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Autem maiores veniam odit <br> 
      necessitatibus quia cum fuga officiis eveniet saepe eligendi, qui repellendus perspiciatis  <br>
      natus consequatur doloribus, alias incidunt. Voluptates, possimus?</p>
    <div class="flex justify-center my-4">
      <%= link_to new_evaluation_path , id: "create_evaluation_welcome", data: {turbo_frame: 'modal'} do%>
        <div class="p-3 bg-evaluationStrong text-white text-sm font-semibold rounded-lg">
         Create evaluation
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/evaluations/edit.html.erb
<%= render 'shared/modal', title: 'Edit Evaluation'  do%>
  <%= render 'form', url: evaluation_path(@evaluation) %>
<% end %>

app/views/evaluations/index.html.erb
<%= turbo_frame_tag 'modal' %>
<% if @evaluations.any? %>
 <%= render 'evaluations', evaluations: @evaluations %>
<% else %> 
 <%= render 'welcome' %>
<% end %> 

app/views/evaluations/new.html.erb
<%= render 'shared/modal', title: 'Create evaluation'  do%>
  <%= render 'form', url: evaluations_path %>
<% end %>

app/views/evaluations/show.html.erb
<%= turbo_frame_tag 'modal' %>
<section id="<%= dom_id @evaluation %>" class="border-2 w-9/12 mx-auto flex h-40 rounded-lg shadow-lg p-2 my-5">
  
  <div class="w-40">
    <%= image_tag("Upload.png", class: "object-fit h-full w-full") %>
  </div>

  <div class="p-5 w-full">
    <p class="text-3xl font-bold text-evaluationStrong">
      <%= @evaluation.name %>
      <i class="fa-solid fa-list-check ml-5"></i>
    </p>

    <p class="my-2 font-semibold text-evaluationStrong">
      Description:
      <%= @evaluation.description %>
    </p>

    <p class="font-semibold text-sm text-evaluationStrong">
      User:
      <%= @evaluation.user_id %>
    </p>
  </div>

  <div class="border-2 flex flex-col justify-between p-2">
    <%= link_to edit_evaluation_path(@evaluation) , id: "edit_evaluation_icon", data: {turbo_frame: 'modal'} do %>
      <i class="fa-solid fa-pen text-editIcon"></i>
    <% end %>  
    <%= button_to evaluation_path(@evaluation), id: 'remove_evaluation_icon', method: :delete,
        form: {data: {turbo_confirm: 'Are you sure?'}} do %>
     <i class="fa-solid fa-trash text-removeIcon"></i>
    <% end %>
  </div>
</section>

<section class="flex m-10 border-2">
  <%= render 'questions/form' %>
  <%= render 'questions/questions', evaluation: @evaluation %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SurveyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.tailwindcss.com"></script>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/main_navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <main class="flex justify-between">
      <div class="w-full">
       <%= yield %>
      </div>
      <nav class="bg-footerGray p-2">
       <%= render 'shared/rigth_navbar' %>  
      </nav>
    </main> 
    <%= render 'shared/footer' %>
  </body>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.4/gsap.min.js"></script>

</html>

app/views/pages/index.html.erb
<section class="flex justify-around h-screen items-center">
  <div>
    <h1 class="text-center font-bold text-mainColor text-3xl">Survey Rails App</h1>
    <p class="text-center text-sm text-mainColor font-semibold">survey-rails-app.com</p>
    <p class="py-5 text-sm font-semibold text-mainColor text-center">
      Lorem ipsum dolor sit amet consectetur adipisicing elit. <br>
      Soluta sit animi itaque hic pariatur. In cupiditate sint,<br> 
      
    </p> 
    <div class="flex w-full justify-around">
      <div class="bg-evaluationStrong p-2 text-white text-sm font-semibold rounded-lg">
        <%= button_to evaluations_path, method: :get, id: "create_evaluation_index" do %>
          Create Evaluation
        <% end %>
      </div>

      <div class="bg-chapterStrong p-2 text-white text-sm font-semibold rounded-lg">
        <%= button_to chapters_path, method: :get, id: "create_evaluation_index" do %>
          Create Chapter
        <% end %>
      </div>
     
    </div>
  </div>
  <div class="flex flex-col justify-center">
    <span class="text-center text-lg font-semibold text-mainColor"> !You are in! </span>
    <%= image_tag("3254897.jpg", width: "400") %>
  </div>
</section>

app/views/pages/landing_page.html.erb
<main>
  <section class="h-96 flex justify-around items-center gap-10 bg-mainColor">
    <div class="text-white text-center">
      <p class="font-semibold text-3xl py-5">
        Survey Rails App MAR.
      </p>
      <p>
        Create your first survey
      </p>
      <p>
        Start sending surveys to differeent companies around the world
      </p>
      <div class="py-5 text-black">
        <%= button_to root_path, id: 'get_started' do %>
        <div class="bg-signIn p-4 rounded-lg">
          <i class="fa-solid fa-circle-arrow-right"></i> 
          <span class="ml-1">
          Get Started
          </span>
        </div>
        <% end %>
      </div>
      <p class="text-sm font-semibold">
         survey-rails-app.com
      </p>
    </div>
    <div>
      <%= image_tag("ruby.png", width: "300")%>
    </div>
  </section>
  <section>
    <div class="flex justify-around p-10">
      <%= image_tag('Amazon.png', width: "70") %>
      <%= image_tag('Facebook.png', width: "70") %>
      <%= image_tag('Google.png', width: "70") %>
      <%= image_tag('Instagram.png', width: "70") %>
      <%= image_tag('LinkedIn.png', width: "70") %>
      <%= image_tag('Spotify.png', width: "70") %>
      <%= image_tag('Twitter.png', width: "70") %>
    </div>

    <p class="text-center text-sm font-semibold text-mainColor p-10">
      Lorem ipsum dolor sit amet consectetur, adipisicing elit. Saepe reiciendis distinctio voluptatem recusandae dolorum, odio perferendis tenetur blanditiis suscipit qui nihil sit quos nostrum numquam maiores consectetur eos. Numquam, consequuntur.
    </p>
  </section>

  <div class="text-center text-sm text-semibold border-2">
    ....
  </div>

  <section class="h-96 flex justify-around items-center">
    <div>
      <%= image_tag('2126918.jpg', width: '350')%>
    </div>
    <div>
      <h2 class="font-semibold text-center text-mainColor text-2xl pb-5">Working with your team!</h2>
      <p class="text-sm text-center text-mainColor font-semibold">
        Lorem ipsum, dolor sit amet consectetur adipisicing <br>
        elit. Quam tenetur eius iste. Velit delectus dicta, <br>
        adipisci, consequuntur autem minus pariatur natus <br>
        provident, minima ea quaerat dignissimos voluptatibus <br>
        obcaecati vel reiciendis.
      </p>
    </div>
  </section>

   <section class="h-96 flex justify-around items-center">
    <div>
      <h2 class="font-semibold text-center text-mainColor text-2xl pb-5">Working with your team!</h2>
      <p class="text-sm text-center text-mainColor font-semibold">
        Lorem ipsum, dolor sit amet consectetur adipisicing <br>
        elit. Quam tenetur eius iste. Velit delectus dicta, <br>
        adipisci, consequuntur autem minus pariatur natus <br>
        provident, minima ea quaerat dignissimos voluptatibus <br>
        obcaecati vel reiciendis.
      </p>
    </div>
    <div>
      <%= image_tag('4048544.jpg', width: '350')%>
      
    </div>
  </section>


  <div class="text-center text-sm text-semibold border-2">
    ....
  </div>

   <section class="h-96 flex flex-col justify-around items-center m-32">
    <div>
      <h2 class="font-semibold text-center text-mainColor text-2xl pb-5">Working with your team!</h2>
    </div>
    <div class="flex p-y-10 w-3/6 justify-between">
       <%= image_tag('2978479.jpg', width: '320')%>
       <%= image_tag('check_box_image.png', width: '250')%>
    </div>
    <div>
     
       <p class="text-sm text-center text-mainColor font-semibold">
        Lorem ipsum, dolor sit amet consectetur adipisicing 
        elit. Quam tenetur eius iste. Velit delectus dicta, 
        adipisci, consequuntur autem minus pariatur natus 
        provident, minima ea quaerat dignissimos voluptatibus 
        obcaecati vel reiciendis.
      </p>
    </div>
  </section>

   <div class="text-center text-sm text-semibold border-2">
    ....
  </div>

  <section class="flex flex-col justify-center h-96 m-32">
    <div>
      <h2 class="font-semibold text-center text-mainColor text-2xl pb-5">!it makes it easiser!</h2>
    </div>
    <div class="flex p-y-10">
       <%= image_tag('posting_image.png')%>
    </div>
    <div>
     
       <p class="text-sm text-center text-mainColor font-semibold">
        Lorem ipsum, dolor sit amet consectetur adipisicing 
        elit. Quam tenetur eius iste. Velit delectus dicta, 
        adipisci, consequuntur autem minus pariatur natus 
        provident, minima ea quaerat dignissimos voluptatibus 
        obcaecati vel reiciendis.
      </p>
    </div>
  </section>


  
</main>

app/views/questions/_form.html.erb
<div class="border-2 w-3/12 m-5">
  <%= form_for  [@evaluation, @question], url: section_create_question_path(@evaluation) do |f| %>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'border-2 w-full' %>
    </div>
    <div>
     <%= f.label :question_type %>
     <%= f.select :question_type, options_for_select(Question.question_types.keys.map { |key, value| [key.titleize, Question.question_types.key(value)] }, @question.question_type) %>
    </div> 
    <div>
      <%= f.submit "Create Question" %>
    </div>
  <% end %>

</div>

app/views/questions/_questions.html.erb
<div class="border-2 w-9/12 m-5" id="questions_all">
  Questions
</div>

app/views/shared/_footer.html.erb
<footer >
 <ul class="flex justify-center gap-10 p-3 bg-footerGray text-sm font-semibold">
  <li>Privacy Policy</li>
  <li>About</li>
  <li>Home</li>
  <li>Sign in</li>
  <li>Sign Up</li>
 </ul>
  <p class="text-center p-4 bg-mainColor text-white">
    Survey Rails app #2023 | Halley Rios
  </p>
</footer>

app/views/shared/_main_navbar.html.erb
<header>
  <nav class="flex justify-between bg-mainColor text-white p-4" >
    <ul >
      <%= link_to root_path , class: "flex gap-3" do %>
        <i class="fa-solid fa-book text-2xl"></i>  Survey Rails App.
      <% end %>
    </ul>
    <ul class="flex gap-3">
      <% if  current_user %>
        <li>
          <%= current_user.email %>
        </li>  
        <li class="bg-red-700 rounded">
          <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: "py-1 px-4 text-sm text-black font-semibold" %>
        </li>
        <li class="flex items-center">
          <%= button_to root_path, id: "open_options_icon" do %>
            <i class="fa-solid fa-gear"></i>
          <% end %>
        </li>
      <% else %>
         <li class="bg-signIn rounded">
          <%= button_to 'Sign in', new_user_session_path, method: :get, class: "py-1 px-4 text-sm text-black font-semibold" %>
        </li>
        <li class="bg-signUp rounded">
          <%= button_to 'Sign up', new_user_registration_path , method: :get, class: 'py-1 px-4 text-sm text-black font-semibold' %>
        </li>  
      <% end %>
     
    </ul>
  </nav>
  
</header>

app/views/shared/_modal.html.erb
<%= turbo_frame_tag 'modal' do%>
  <section class="absolute z-10 top-0 left-0 h-screen bg-mainColor w-full opacity-90 flex justify-center items-center">
    <div class="p-24 border-2 rounded-lg bg-black w-3/5">
      <h2 class="text-xl text-white font-semibold py-5 text-center"><%=title%></h2>
      <%= yield %>
    </div>
  </section>
<% end %>

app/views/shared/_rigth_navbar.html.erb
<ul class="flex flex-col justify-center p-2">
  <li class="flex justify-center">
    <%= link_to root_path, id: "home_icon" do %>
      <i class="fa-solid fa-house"></i>
    <% end %>
  </li>
  <li class="flex justify-center p-2">
    <%= link_to root_path, id: "evaluation_icon" do %>
      <i class="fa-solid fa-list-check"></i>
    <% end %>
  </li>
  <li class="flex justify-center p-2">
    <%= link_to root_path, id: "chapters_icon" do %>
      <i class="fa-solid fa-square-poll-horizontal"></i>
    <% end %>
  </li>
  <li class="flex justify-center p-2">
    <%= link_to root_path, id: "surveys_icon" do %>
      <i class="fa-solid fa-folder-open"></i>
    <% end %>
  </li>
</ul>